"""Freeze a held-out evaluation set, disjoint from the regression fixtures, for model-configuration decisions.

Takes the next six qualifying rows after the regression selection from the same immutable
dataset revisions (FLEURS cmn_hans_cn / en_us test, ASCEND test rows with both scripts) plus six
generated non-speech cases with different seeds. Written to evaluation/ with its own manifest;
regression/ is never touched. Build-time only.
"""
import io
import json
import math
import random
import re
import struct
import wave
from bootstrap import ROOT, sha256
import pyarrow.parquet as pq
import soundfile as sf
from acquire_fixtures import RangeFile, SOURCES

EVAL = ROOT / 'evaluation'

def main():
    EVAL.mkdir(exist_ok=True)
    manifest_path = EVAL / 'manifest.json'
    if manifest_path.exists():
        raise SystemExit('Held-out IDs already frozen; refusing to select a different set.')
    regression = json.loads((ROOT / 'regression/manifest.json').read_text('utf-8'))
    used = {(f['dataset'], f['config'], f['row']) for f in regression['fixtures'] if 'dataset' in f}
    records, audio_bytes = [], {}
    for group, dataset, config, revision, size, license_name in SOURCES:
        url = f'https://huggingface.co/datasets/{dataset}/resolve/{revision}/{config}/test/0000.parquet'
        parquet = pq.ParquetFile(RangeFile(url, size, ROOT / '.cache/datasets' / group))
        selected, row_idx = 0, 0
        for batch in parquet.iter_batches(batch_size=100):
            for row in batch.to_pylist():
                text = row.get('raw_transcription', row.get('transcription', ''))
                mixed = bool(re.search(r'[㐀-鿿]', text) and re.search(r'[A-Za-z]+', text))
                if (group != 'mixed' or mixed) and (dataset, config, row_idx) not in used:
                    # skip rows the regression set would have chosen (they are in `used`); take the next six
                    fixture_id = f'heldout-{group}-{row_idx:04d}'
                    records.append({'id': fixture_id, 'category': group, 'row': row_idx, 'dataset': dataset, 'dataset_revision': revision, 'config': config,
                                    'split': 'test', 'source_id': str(row.get('id', row.get('path', row_idx))), 'human_text': text, 'license': license_name, 'source_url': url})
                    audio_bytes[fixture_id] = row['audio']['bytes']
                    selected += 1
                row_idx += 1
                if selected == 6: break
            if selected == 6: break
        if selected != 6: raise RuntimeError(f'Not enough held-out rows for {group}')
    for entry in records:
        samples, rate = sf.read(io.BytesIO(audio_bytes[entry['id']]), dtype='float32', always_2d=True)
        path = EVAL / (entry['id'] + '.wav')
        sf.write(path, samples, rate, subtype='PCM_16')
        entry.update(path=path.name, sha256=sha256(path), duration_seconds=len(samples) / rate, conversion='Decoded dataset audio, preserved sample rate/channels, PCM16 WAV')
    for i, (name, duration) in enumerate([('silence-short', 0.7), ('silence', 3), ('silence-long', 12), ('low-noise', 4), ('tone', 3), ('clicks', 5)]):
        rng = random.Random(20260908 + i)
        samples = []
        for n in range(int(duration * 16000)):
            value = 0
            if name == 'low-noise': value = rng.randint(-25, 25)
            if name == 'tone': value = int(1200 * math.sin(2 * math.pi * 700 * n / 16000))
            if name == 'clicks' and n % 6000 < 120: value = rng.randint(-1200, 1200)
            samples.append(value)
        path = EVAL / f'heldout-{name}.wav'
        with wave.open(str(path), 'wb') as w:
            w.setparams((1, 2, 16000, 0, 'NONE', 'not compressed'))
            w.writeframes(struct.pack('<' + 'h' * len(samples), *samples))
        records.append({'id': f'heldout-{name}', 'category': 'non-speech', 'path': path.name, 'sha256': sha256(path), 'human_text': '', 'license': 'CC0-1.0',
                        'duration_seconds': duration, 'source': 'Deterministically generated by scripts/acquire_heldout.py'})
    manifest = {'schema': 1, 'purpose': 'held-out evaluation for model-configuration decisions; disjoint from regression/',
                'selection_policy': 'Next six qualifying test rows after the regression selection per source; six generated non-speech cases with new seeds.',
                'fixtures': records}
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print('Frozen 24 held-out evaluation cases.')

if __name__ == '__main__':
    main()
