"""Generate docs/PROOF.md and docs/BENCHMARK.md from the measured reports.

Every number in the generated documents comes from a JSON report under reports/ or a lock
file. Missing reports are reported as "not measured" rather than invented.
"""
import json
import statistics
from pathlib import Path
from bootstrap import ROOT
from shipped import CONFIG, MODEL_DIR, remote
REPORTS = ROOT / CONFIG.get('report_root','reports')

def load(rel):
    path = REPORTS / rel[len('reports/'):] if rel.startswith('reports/') and rel!='reports/package.json' else ROOT / rel
    return json.loads(path.read_text('utf-8')) if path.exists() else None

def fmt(value, digits=3):
    if value is None: return 'n/a'
    if isinstance(value, bool): return 'yes' if value else 'no'
    if isinstance(value, int): return str(value)
    return f'{value:.{digits}f}'

def gib(value): return 'n/a' if value is None else f'{value / 2**30:.2f} GiB ({value / 1e9:.2f} GB)'

def percentile(values, p):
    if not values: return None
    values = sorted(values)
    index = min(len(values) - 1, max(0, int(round(p * len(values) + 0.5)) - 1))
    return values[index]

lock = load('dependencies.lock.json')
model_manifest = load(CONFIG['model_dir'] + '/manifest.json')
reference_lock = remote('reference_lock_key')
previous = load(CONFIG['previous_proof'] + '/summary.json') if CONFIG.get('previous_proof') else None
remote = load('remote-assets.lock.json')
verification = load('reports/verification.json')
manifest = load('regression/manifest.json')
policy = load('verification-policy.json')
boundaries = load('reports/boundaries.json')
encoder_diff = load('reports/encoder-diff-mandarin-0000.json')
tokenizer = load('reports/tokenizer.json')
preprocessing = load('reports/preprocessing.json')
frontend = load('reports/fixture-frontend.json')
gate = load('reports/speech-gate.json')
cli = load('reports/cli-failures.json')
threads = load('reports/benchmark-threads.json')
memory = load('reports/memory.json')
package = load('reports/package.json')
environment = load('reports/environment.json')
directml = load('reports/directml.json')
live = {p.stem: json.loads(p.read_text('utf-8')) for p in sorted(REPORTS.glob('live-*.json')) if 'overload' not in p.stem and 'slow' not in p.stem}
fault = load('reports/live-overload-test.json')
captures = {p.stem: json.loads(p.read_text('utf-8')) for p in sorted(REPORTS.glob('capture-*.json')) if not p.stem.endswith('-scored')}
stages = {p.stem: json.loads(p.read_text('utf-8')) for p in sorted((REPORTS / 'stages').glob('*.json'))}
categories = {f['id']: f['category'] for f in manifest['fixtures']} if manifest else {}

out = []
w = out.append
w('# Transcription proof report')
w('')
w('Generated by `scripts/proof_report.py` from the JSON reports under `reports/`. Numbers are measurements on the reference PC described below; nothing here is a clean-install or portability claim.')
w('')
w('## 1. Frozen assets')
w('')
w('| Asset | Source | Revision | Bytes | SHA-256 |')
w('|---|---|---|---|---|')
if model_manifest:
    for item in model_manifest['files']:
        w(f"| `{item['path']}` | {model_manifest['source_model']['repo']} | `{model_manifest['source_model']['revision'][:12]}` | {item['bytes']:,} | `{item['sha256']}` |")
if lock:
    for key in ['onnx-export', 'qwen-reference', 'tokenizers-cpp', 'kissfft', 'libfvad', 'json']:
        info = lock['sources'][key]; digest = lock['files'].get(f'.deps/archives/{key}.zip', {})
        w(f"| `{key}` source snapshot | {info['repo']} | `{info['revision'][:12]}` | {digest.get('bytes', 0):,} | `{digest.get('sha256', 'n/a')}` |")
    ort = lock['files'].get('.deps/archives/onnxruntime.zip', {})
    w(f"| ONNX Runtime package | {lock['onnxruntime']['package']} {lock['onnxruntime']['version']} | NuGet | {ort.get('bytes', 0):,} | `{ort.get('sha256', 'n/a')}` |")
    for asset in reference_lock['files']:
        if asset['path'].endswith('.safetensors'):
            w(f"| reference `{asset['path']}` | {reference_lock['repo']} | `{reference_lock['revision'][:12]}` | {asset['bytes']:,} | `{asset['sha256']}` |")
w('')
w('`mel_filters.bin` and `prompt_reference.json` are generated from the official `Qwen3ASRProcessor` (`scripts/reference.py --prepare-only`). Publisher-supplied LFS hashes for the ONNX and safetensors assets were checked by `scripts/check_publisher_hashes.py` (`reports/publisher-hashes.json`).')
w('')
w(f"Shipped configuration: **{CONFIG['configuration']}** (`{CONFIG['model_dir']}`). {CONFIG.get('note', '')}")
w(f"Evidence collection: `{CONFIG.get('report_root','reports')}`. Historical reports remain in the archived model collections; see `docs/RESUME-AUDIT.md` for which checks were rerun after fixes.")
w('')
if previous:
    w(f"Archived proof of the previous configuration ({previous.get('configuration')}): {previous.get('summary')} Reports are under `{CONFIG['previous_proof']}/`.")
    w('')
w('## 2. Reference oracle and the encoder attention window')
w('')
w('The oracle is the unmodified official `Qwen3ASRProcessor` and `Qwen3ASRForConditionalGeneration` from the pinned QwenLM/Qwen3-ASR revision, FP32, eager attention, greedy decoding, on CPU. One documented adjustment is applied through the layer call, not by editing the official source:')
w('')
w('- The official `Qwen3ASRAudioEncoder` defines `_prepare_attention_mask` (block-diagonal windows of `n_window_infer = 800` mel frames = 104 encoder tokens) and passes `cu_seqlens` to every layer, but the eager/SDPA path never applies the mask, so the encoder attends globally across the whole utterance. The flash-attention path of the same file and the transformers-integrated implementation (`get_audio_cu_seqlens`, per-window attention on the non-flash path) both attend within windows, and the pinned ONNX export implements the windowed behaviour.')
w("- `scripts/reference.py` therefore applies the official `_prepare_attention_mask` output when a layer is called without a mask. `--global-attention` reproduces the unmasked pinned path; its outputs are kept in `reports/reference-global-attention/` for comparison.")
if encoder_diff:
    w('')
    w(f"Measured on `{encoder_diff['fixture']}` ({encoder_diff['mel_frames']} mel frames, {encoder_diff['tokens']} encoder tokens):")
    w('')
    w('| Comparison | max abs error | RMSE | reference RMS |')
    w('|---|---|---|---|')
    for c in encoder_diff['comparisons']:
        w(f"| {c['pair'].replace('_', ' ')} | {c['max_abs']:.2e} | {c['rmse']:.2e} | {c['reference_rms']:.4f} |")
global_refs = {p.stem: json.loads(p.read_text('utf-8')) for p in (REPORTS / 'reference-global-attention').glob('*.json') if p.stem != 'manifest'}
if global_refs:
    same = [k for k, v in global_refs.items() if (ROOT / 'regression/reference' / f'{k}.json').exists() and json.loads((ROOT / 'regression/reference' / f'{k}.json').read_text('utf-8'))['text'] == v['text']]
    same_tokens = [k for k, v in global_refs.items() if (ROOT / 'regression/reference' / f'{k}.json').exists() and json.loads((ROOT / 'regression/reference' / f'{k}.json').read_text('utf-8'))['tokens'] == v['tokens']]
    w('')
    w(f'Windowed and global oracle transcripts are identical on {len(same)} of {len(global_refs)} fixtures; token sequences are identical on {len(same_tokens)} of {len(global_refs)}. The remaining cases include transcript differences; the window-mask adjustment is part of the documented oracle definition.')
w('')
w('## 3. Stage-by-stage verification')
w('')
if tokenizer: w(f"- Tokenizer: {sum(1 for c in tokenizer['cases'] if c['match'])}/{len(tokenizer['cases'])} frozen prompt/text/EOS cases match the official tokenizer (`reports/tokenizer.json`). The executable re-checks these cases at every model load.")
if preprocessing: w(f"- Preprocessing: {sum(1 for c in preprocessing['cases'] if c['success'])}/{len(preprocessing['cases'])} boundary, PCM-format and resampling cases pass (`reports/preprocessing.json`).")
if frontend: w(f"- Fixture frontend: {sum(1 for c in frontend['fixtures'] if c['success'])}/{len(frontend['fixtures'])} fixtures match the official mel features and audio-token counts (`reports/fixture-frontend.json`).")
if gate: w(f"- Speech gate: {sum(1 for c in gate['cases'] if c['success'])}/{len(gate['cases'])} non-speech cases produce no segments (`reports/speech-gate.json`).")
if cli: w(f"- Invalid input: {sum(1 for c in cli['cases'] if c['success'])}/{len(cli['cases'])} malformed-input and missing-asset cases exit nonzero with explicit errors (`reports/cli-failures.json`).")
w('')
w('Tolerances (`verification-policy.json`):')
w('')
if policy:
    w('| Stage | absolute | relative (per element) | scale-relative (× max|ref|) | RMSE-relative (× RMS ref) |'); w('|---|---|---|---|---|')
    for k, v in policy['stages'].items(): w(f"| {k} | {v['absolute']} | {v['relative']} | {v.get('scale_relative', '-')} | {v.get('rmse_relative', '-')} |")
    w(''); w(policy.get('criteria', ''))
    for change in policy.get('tolerance_changes', []):
        w(''); w(f"Tolerance change ({change['date']}, {', '.join(change['stages'])}): {change['change']}. Reason: {change['reason']}")
w('')
if verification:
    w('### Regression set (24 fixtures, `reports/verification.json`)')
    w('')
    w(f"Model load {fmt(verification.get('model_load_seconds'), 1)} s including asset hashing; provider {verification['engine']['provider']}, {verification['engine']['threads']} intra-op threads, ONNX Runtime {verification['engine']['runtime']}.")
    w('')
    w('| Fixture | Category | Completion | Tokens exact | Transcript match | Stage max errors (encoder / logits_0 / keys_0 / values_0) | Stages | Human CER/WER | Inference s | RTF |')
    w('|---|---|---|---|---|---|---|---|---|---|')
    for row in verification['fixtures']:
        obs = row.get('observed', {}); st = stages.get(row['id'], {}); s = st.get('stages', {})
        errors = ' / '.join(f"{s[k]['max_absolute_error']:.1e}" if k in s and 'max_absolute_error' in s[k] else '-' for k in ['encoder', 'logits_0', 'keys_0', 'values_0'])
        human = row.get('human_error', {}).get('rate')
        w(f"| {row['id']} | {categories.get(row['id'], '')} | {obs.get('completion', row.get('error', 'error'))} | {fmt(row.get('tokens_exact'))} | {fmt(row.get('normalized_transcript_match'))} | {errors} | {fmt(st.get('success')) if st else 'n/a'} | {fmt(human, 3) if human is not None else '-'} | {fmt(obs.get('total_seconds'), 2)} | {fmt(obs.get('rtf'), 2)} |")
    passed = sum(1 for r in verification['fixtures'] if r.get('success'))
    tokens_exact = sum(1 for r in verification['fixtures'] if r.get('tokens_exact'))
    stages_pass = sum(1 for r in verification['fixtures'] if stages.get(r['id'], {}).get('success'))
    w('')
    w(f'Transcript-level pass: {passed}/24. Token sequences identical to the oracle: {tokens_exact}/24. All numerical stages within tolerance: {stages_pass}/24.')
    diffs = [(r['id'], stages[r['id']]['token_differences']) for r in verification['fixtures'] if stages.get(r['id']) and stages[r['id']].get('token_differences')]
    if diffs:
        w(''); w('Token differences:'); w('')
        for id_, d in diffs: w(f'- {id_}: {d}')
    for cat, char in [('mandarin', True), ('english', False), ('mixed', False)]:
        rates = [r['human_error']['rate'] for r in verification['fixtures'] if categories.get(r['id']) == cat and r.get('human_error', {}).get('rate') is not None]
        edits = sum(r['human_error']['edits'] for r in verification['fixtures'] if categories.get(r['id']) == cat and r.get('human_error'))
        units = sum(r['human_error']['reference_units'] for r in verification['fixtures'] if categories.get(r['id']) == cat and r.get('human_error'))
        if units:
            label = {'mandarin': 'Mandarin CER (characters)', 'english': 'English WER (words)', 'mixed': 'Mixed MER (characters + words)'}[cat]
            w(f'- {label} against human transcripts: {edits}/{units} = {edits / units:.3f} pooled (per-fixture mean {statistics.mean(rates):.3f}). Displayed text is unchanged; normalization is applied only for scoring as documented in `verification-policy.json`.')
    silence = [r for r in verification['fixtures'] if categories.get(r['id']) == 'non-speech']
    w(f"- Raw-model silence/non-speech: {sum(1 for r in silence if r.get('observed', {}).get('text') == '' and r.get('observed', {}).get('completion') == 'eos')}/{len(silence)} fixtures produce empty output with EOS through the model itself; the application speech gate additionally emits no segments for them.")
w('')
if boundaries:
    w('### Boundary and session cases (`reports/boundaries.json`)')
    w('')
    w('| Case | Audio tokens | Native text | Tokens exact | Stages | Result |'); w('|---|---|---|---|---|---|')
    for c in boundaries['cases']:
        if c['case'] == 'repeat-interleaved':
            w(f"| repeat-interleaved (5× same file interleaved with another) | - | tokens identical across runs: {fmt(c.get('tokens_identical_across_runs'))}, equal to reference: {fmt(c.get('matches_reference_tokens'))} | - | - | {'PASS' if c['success'] else 'FAIL'} |")
        else:
            w(f"| {c['case']} | {c.get('audio_tokens')} | {c.get('native_text')} | {fmt(c.get('tokens_exact'))} | {fmt(c.get('stages_success'))} | {'PASS' if c['success'] else 'FAIL'} |")
    w('')
    w('Every generation owns fresh cache state; cache shape and one-token growth are checked at each step. Provisional decoding recomputes the prefill for each audio snapshot.')
w('')
w('## 4. Memory and timing')
w('')
if verification:
    peaks = [r['observed']['memory']['peak_working_set_bytes'] for r in verification['fixtures'] if r.get('observed', {}).get('memory')]
    if peaks: w(f'- Peak working set during verification: {gib(max(peaks))}; after model load: {gib(verification.get("memory_after_load", {}).get("peak_working_set_bytes"))}.')
if memory:
    w('- Session memory configurations (`reports/memory.json`):'); w('')
    w('| Configuration | Peak working set | Private bytes | Load s | Inference s (same fixture) | Tokens identical |'); w('|---|---|---|---|---|---|')
    for r in memory['runs']: w(f"| {r['configuration']} | {gib(r['peak_working_set_bytes'])} | {gib(r['private_bytes'])} | {fmt(r['model_load_seconds'], 1)} | {fmt(r['total_seconds'], 2)} | {fmt(r.get('tokens_identical'))} |")
    w(''); w(f"Selected: {memory.get('selected')}.")
if threads:
    w(''); w('- CPU thread budget (`reports/benchmark-threads.json`, same fixtures, provider CPU):'); w('')
    w('| Threads | Mean RTF | Mean decode ms/token | Mean prefill s | Mean encoder s |'); w('|---|---|---|---|---|')
    for r in threads['summary']: w(f"| {r['threads']} | {fmt(r['rtf'], 3)} | {fmt(r['decode_ms_per_token'], 1)} | {fmt(r['prefill_seconds'], 3)} | {fmt(r['encoder_seconds'], 3)} |")
    w(''); w(f"Selected thread budget: {threads.get('selected')} ({threads.get('reason', '')}).")
variants = load('reports/variant-evaluation.json')
if variants:
    w(''); w('- Model configuration (held-out evaluation set `evaluation/`, disjoint from the regression fixtures; `reports/variant-evaluation.json`):'); w('')
    w('| Variant | Mandarin CER | English WER | Mixed MER | Non-speech failures | Mean RTF | Peak working set | Decision |'); w('|---|---|---|---|---|---|---|---|')
    for name, r in variants['results'].items():
        cats = r['categories']; d = variants['decisions'].get(name)
        decision = 'baseline' if name == 'fp32' else ('accepted' if d and d['accepted'] else 'rejected')
        w(f"| {name} | {fmt(cats.get('mandarin', {}).get('error_rate'), 3)} | {fmt(cats.get('english', {}).get('error_rate'), 3)} | {fmt(cats.get('mixed', {}).get('error_rate'), 3)} | {len(r['silence_failures'])} | {fmt(r['mean_rtf'], 3)} | {gib(r['peak_working_set_bytes'])} | {decision} |")
    w(''); w(f"Rule: {variants['rule']}.")
    for name, d in variants['decisions'].items():
        diffs = d.get('fixtures_differing_from_baseline', [])
        if diffs:
            w(''); w(f'Fixtures where `{name}` differs from the FP32 baseline (all other speech fixtures produced identical text):'); w('')
            w('| Fixture | FP32 text | Candidate text | Edits vs human (FP32 → candidate) |'); w('|---|---|---|---|')
            for x in diffs: w(f"| {x['id']} | {x['baseline_text']} | {x['candidate_text']} | {x['baseline_edits']} → {x['candidate_edits']} |")
            w(''); w('Scoring normalization does not convert numerals, so a different rendering of the same number (Arabic digits versus Chinese numerals) counts as character edits against the human transcript; the rule above is applied as written.')
    shipped = model_manifest
    if shipped: w(f"Shipped configuration (model manifest): {shipped.get('configuration')}.")
if directml:
    w(''); w(f"- DirectML: {directml.get('summary', 'see reports/directml.json')}")
else:
    w(''); w('- DirectML: not enabled. `--provider directml` is rejected unless `--experimental-directml` is given for benchmark experiments; the interface always uses the CPU provider.')
w('')
w('## 5. Live pipeline measurements')
w('')
if live:
    w('Simulated live runs replay a fixture through the capture ring, resampler, speech gate and scheduler in real time (`--benchmark file --simulate-live`).'); w('')
    w('| Run | Audio s | Finals | Provisional lag p50 / p95 / max s | First caption p95 s | Finalization p95 s | Max backlog s | Peak working set | Result |'); w('|---|---|---|---|---|---|---|---|---|')
    for name, r in live.items():
        s = r['live']; p = s['provisional_lag_seconds']
        w(f"| {name} | {fmt(r['source'].get('audio_seconds'), 1)} | {s['final_count']} | {fmt(p['p50'], 2)} / {fmt(p['p95'], 2)} / {fmt(p['max'], 2)} | {fmt(s['first_caption_lag_seconds']['p95'], 2)} | {fmt(s['finalization_delay_seconds']['p95'], 2)} | {fmt(s['pipeline']['max_backlog_seconds'], 2)} | {gib(s['pipeline']['memory']['peak_working_set_bytes'])} | {'PASS' if r['success'] else 'FAIL'} |")
if captures:
    w(''); w('Loopback captures use the real WASAPI path on the reference PC while a player renders audio to the selected endpoint (`--capture`).'); w('')
    w('| Run | Device | Duration s | Finals | Provisional lag p95 s | First caption p95 s | Finalization p95 s | Max backlog s | Discontinuities | Dropped frames | CPU load | Peak working set | Result |'); w('|---|---|---|---|---|---|---|---|---|---|---|---|---|')
    for name, r in captures.items():
        s = r['live']; c = s['pipeline'].get('capture', {})
        cpu = s['pipeline']['process_cpu_seconds'] / max(1e-9, s['pipeline']['wall_seconds'])
        w(f"| {name} | {r['source'].get('device')} | {fmt(s['pipeline']['wall_seconds'], 0)} | {s['final_count']} | {fmt(s['provisional_lag_seconds']['p95'], 2)} | {fmt(s['first_caption_lag_seconds']['p95'], 2)} | {fmt(s['finalization_delay_seconds']['p95'], 2)} | {fmt(s['pipeline']['max_backlog_seconds'], 2)} | {c.get('discontinuities')} | {c.get('dropped_frames')} | {cpu:.2f} cores | {gib(s['pipeline']['memory']['peak_working_set_bytes'])} | {'PASS' if r['success'] else 'FAIL'} |")
scored = {p.stem.replace('-scored', ''): json.loads(p.read_text('utf-8')) for p in sorted((ROOT / 'reports').glob('capture-*-scored.json'))}
if scored:
    w(''); w('Caption accuracy of the loopback captures, finals assigned to played clips by time overlap (pooled edit rates; Mandarin characters, English words, mixed characters+words):'); w('')
    w('| Run | Background load | Mandarin vs oracle / human | English vs oracle / human | Mixed vs oracle / human | Clips without caption |'); w('|---|---|---|---|---|---|')
    for name, r in scored.items():
        sm = r['summary']
        cell = lambda cat: f"{fmt(sm[cat]['oracle_error_rate'], 3)} / {fmt(sm[cat]['human_error_rate'], 3)}" if cat in sm else 'n/a'
        w(f"| {name} | {r.get('background_load_processes')} busy processes | {cell('mandarin')} | {cell('english')} | {cell('mixed')} | {sum(v['clips_without_caption'] for v in sm.values())} of {sum(v['clips'] for v in sm.values())} |")
gui = load('reports/gui-test.json')
if gui:
    w(''); w(f"Interface test (`scripts/gui_test.py`, Win32 messages against the running window): {'PASS' if gui['success'] else 'FAIL'} — " + '; '.join(f"{s['step']}: {'ok' if s['success'] else 'FAIL'}" for s in gui['steps']) + '.')
    detail = {s['step']: s for s in gui['steps']}
    if 'model loads' in detail: w(f"Model load in the interface: {detail['model loads'].get('load_seconds')} s; first provisional caption {detail.get('first provisional caption appeared', {}).get('seconds_after_playback_start')} s after playback started (first clip starts at {detail.get('first provisional caption appeared', {}).get('first_clip_start')} s).")
if fault:
    fs = fault['live']; fp = fs['pipeline']
    slow = load('reports/live-slow3-test.json')
    if slow:
        ss = slow['live']; spp = ss['pipeline']
        w(''); w(f"Fault injection, moderate (`--simulate-live --slow-inference {slow.get('options', {}).get('slow_inference', '?')}`): stop reason \"{spp.get('stop_reason')}\", {spp.get('suspensions')} provisional suspensions (\"Catching up\"), max backlog age {fmt(spp.get('max_backlog_seconds'), 1)} s, finals {ss['final_count']}, duplicate finals {ss.get('duplicate_finals')}, stale provisionals delivered {ss.get('stale_provisionals_delivered')} — finalization falls behind, provisional decoding is suspended and resumes, no overload stop is needed.")
    w(''); w(f"Fault injection, severe (`--simulate-live --slow-inference {fault.get('options', {}).get('slow_inference', '?')}`, every generation delayed): stop reason \"{fp.get('stop_reason')}\", {fp.get('suspensions')} provisional suspensions, max backlog {fmt(fp.get('max_backlog_seconds'), 1)} s, finals delivered {fs['final_count']}, duplicate finals {fs.get('duplicate_finals')}, stale provisionals delivered {fs.get('stale_provisionals_delivered')}, audio loss {'no' if fs.get('no_audio_loss') else 'yes'}. Expected behaviour: provisional decoding suspended above 4 s of backlog, capture stopped visibly above 20 s, remaining audio drained and finalized exactly once.")
if not live and not captures:
    w('Not measured yet.')
w('')
w('## 6. Package')
w('')
if package:
    w(f"`{package['package']}`: {package['files']} files. Exact extracted/archive sizes and the archive SHA-256 are published in the release-info JSON beside the archive. They are kept outside the ZIP to avoid a self-referential archive hash.")
else:
    w('Not built yet.')
w('')
w('## 7. Acceptance target and remaining gaps')
w('')
w('Initial real-time target on the reference PC: p95 provisional lag ≤ 4 s, bounded backlog without overload stops, no application audio loss, peak process memory ≤ 16 GB.')
w('')
runs = {**live, **captures}
if runs:
    w('| Run | p95 provisional lag s | Overload stop | Audio loss | Peak working set | Target met |'); w('|---|---|---|---|---|---|')
    for name, r in runs.items():
        sp = r['live']; pipe = sp['pipeline']; cap = pipe.get('capture', {})
        p95 = sp['provisional_lag_seconds']['p95']
        overload = str(pipe.get('stop_reason', '')).startswith('Overload') or str(pipe.get('stop_reason', '')).startswith('Retained')
        loss = cap.get('dropped_frames', 0) or cap.get('overflow_events', 0)
        peak = pipe['memory']['peak_working_set_bytes']
        met = r.get('success',False) and sp['provisional_lag_seconds']['count']>0 and p95 <= 4.0 and not overload and not loss and peak <= 16_000_000_000
        w(f"| {name} | {fmt(p95, 2)} | {fmt(overload)} | {fmt(bool(loss))} | {gib(peak)} | {'yes' if met else 'no'} |")
    failing = [name for name, r in runs.items() if r['live']['provisional_lag_seconds']['p95'] > 4.0]
    w('')
    if failing:
        w(f"The p95 provisional-lag target is **not met** in {len(failing)} of {len(runs)} runs ({', '.join(failing)}): with the FP32 1.7B decoder at about 140 ms per token, a provisional decode of a 10–15 s Mandarin snapshot takes 3–5 s, and finalization of a 15 s utterance 5–9 s. The int4 decoder is about 3× faster but was rejected by the held-out accuracy rule (section 4); this limitation is published as measured. Memory is reported in both binary and decimal units because the target does not state which; the peak is below 16 GiB and slightly above 16 GB.")
    else:
        w('The p95 provisional-lag target is met in every measured run.')
w('')
w('Remaining gaps:')
w('')
w('- Clean-Windows verification on external machines has not been performed; the package is a test candidate and no clean-install or real-time support claim is made.')
w('- DirectML is disabled: it has not passed regression and sustained-load tests on any adapter/driver combination.')
w('- Sustained live measurements exist only for the reference PC; see `docs/COMPATIBILITY.md`.')
(ROOT / 'docs/PROOF.md').write_text('\n'.join(out) + '\n', encoding='utf-8')

bench = []
b = bench.append
b('# Benchmark report (reference PC)')
b('')
if environment:
    b(f"Measured on {environment['cpu']['Name'].strip()} ({environment['cpu']['NumberOfCores']} cores / {environment['cpu']['NumberOfLogicalProcessors']} threads), {environment['os']['TotalVisibleMemorySize'] // 1024 // 1024} GiB RAM, {environment['os']['Caption']} build {environment['os']['BuildNumber']}. GPU: {', '.join(g['Name'] for g in environment['graphics'] if 'Radeon' in g['Name'])} (unused; CPU provider).")
    b('')
if verification:
    rows = [r['observed'] for r in verification['fixtures'] if r.get('observed') and categories.get(r['id']) != 'non-speech']
    if rows:
        b('## File transcription (`--verify`, 24 fixtures, CPU)'); b('')
        b(f"- Speech fixtures: mean RTF {statistics.mean(r['rtf'] for r in rows):.3f}, max RTF {max(r['rtf'] for r in rows):.3f}; mean encoder {statistics.mean(r['encoder_seconds'] for r in rows):.3f} s, mean prefill {statistics.mean(r['prefill_seconds'] for r in rows):.3f} s, mean decode {statistics.mean(r['decode_seconds'] / max(1, len(r['tokens'])) * 1000 for r in rows):.1f} ms/token.")
        b(f"- Model load {fmt(verification.get('model_load_seconds'), 1)} s (includes SHA-256 of {sum(i['bytes'] for i in model_manifest['files']) / 1e9:.1f} GB of assets).")
        b('')
if threads:
    b('## Thread budget'); b('')
    b('| Threads | Mean RTF | Decode ms/token | Prefill s | Encoder s |'); b('|---|---|---|---|---|')
    for r in threads['summary']: b(f"| {r['threads']} | {fmt(r['rtf'], 3)} | {fmt(r['decode_ms_per_token'], 1)} | {fmt(r['prefill_seconds'], 3)} | {fmt(r['encoder_seconds'], 3)} |")
    b(''); b(f"Selected: {threads.get('selected')} threads. {threads.get('reason', '')}"); b('')
if memory:
    b('## Memory'); b('')
    for r in memory['runs']: b(f"- {r['configuration']}: peak working set {gib(r['peak_working_set_bytes'])}, private {gib(r['private_bytes'])}, load {fmt(r['model_load_seconds'], 1)} s, inference {fmt(r['total_seconds'], 2)} s.")
    b(''); b(f"Selected: {memory.get('selected')}."); b('')
if live or captures:
    b('## Live pipeline'); b('')
    for name, r in {**live, **captures}.items():
        s = r['live']; p = s['provisional_lag_seconds']
        b(f"- {name}: {s['final_count']} finals, provisional lag p95 {fmt(p['p95'], 2)} s (max {fmt(p['max'], 2)} s), first caption p95 {fmt(s['first_caption_lag_seconds']['p95'], 2)} s, finalization p95 {fmt(s['finalization_delay_seconds']['p95'], 2)} s, max backlog {fmt(s['pipeline']['max_backlog_seconds'], 2)} s, {s['pipeline'].get('suspensions')} suspensions, stop reason \"{s['pipeline'].get('stop_reason')}\", peak working set {gib(s['pipeline']['memory']['peak_working_set_bytes'])}, CPU {s['pipeline']['process_cpu_seconds'] / max(1e-9, s['pipeline']['wall_seconds']):.2f} cores average.")
    b('')
if package:
    b('## Package size'); b('')
    b('- Exact extracted bytes, compressed bytes and SHA-256: see the release-info JSON beside the portable ZIP.');
    b('')
b('## Acceptance target')
b('')
b('Initial real-time target: p95 provisional lag ≤ 4 s, bounded backlog without overload stops, no application audio loss, peak process memory ≤ 16 GB on the reference PC. See the live pipeline section for the measured values and `docs/PROOF.md` §7 for failures and limitations.')
(ROOT / 'docs/BENCHMARK.md').write_text('\n'.join(bench) + '\n', encoding='utf-8')
compat = []
c = compat.append
c('# Compatibility matrix')
c('')
c('Only configurations listed as tested were actually exercised. Everything else is untested; no support claim is made for it.')
c('')
c('| Windows build / edition | Architecture | CPU | RAM | GPU / driver | Provider | Tested how | Result |')
c('|---|---|---|---|---|---|---|---|')
if environment:
    gpus = '; '.join(f"{g['Name']} {g['DriverVersion']}" for g in environment['graphics'] if 'Radeon' in g['Name'])
    tested = ['transcription proof (`--verify`, 24 fixtures)'] + (['boundary/session cases'] if boundaries else []) + ([f'{len(live)} simulated live runs'] if live else []) + ([f'{len(captures)} WASAPI loopback captures'] if captures else []) + (['interface test'] if load('reports/gui-test.json') else [])
    result = 'proof passed' if verification and verification.get('success') and len(stages)==24 and all(s.get('success') for s in stages.values()) and boundaries and boundaries.get('success') else 'proof incomplete'
    c(f"| {environment['os']['Caption']} {environment['os']['Version']} (build {environment['os']['BuildNumber']}) — development host, not a clean install | x64 | {environment['cpu']['Name'].strip()} | {environment['os']['TotalVisibleMemorySize'] // 1024 // 1024} GiB | {gpus} (present, unused) | CPU | {', '.join(tested)} | {result}; live measurements in docs/BENCHMARK.md |")
c('| Windows 10 22H2 x64 | x64 | any | ≥16 GB | any | CPU | **not tested** | untested |')
c('| Windows 11 24H2 x64 (clean install, standard user, offline) | x64 | any | ≥16 GB | any | CPU | **not tested** — pending external clean-machine run | untested |')
c('| Windows N editions without Media Feature Pack | x64 | any | any | any | CPU | excluded (Windows Audio Resampler requires Media Foundation) | unsupported |')
c('| Any | x64 | any | any | any | DirectML | not enabled in this version | unsupported |')
c('')
c('## What "tested" covered on the development host')
c('')
c('- Command-line transcription of the 24 frozen fixtures against the official model, stage-by-stage numerical comparison, boundary and repeated-session cases.')
c('- Live pipeline: simulated real-time replay through the capture ring and scheduler, real WASAPI loopback capture of a player rendering to the default endpoint with background CPU load, and the interface driven through Win32 messages.')
c('- The package manifest check (`--check-package`) on the assembled folder.')
c('')
c('## Not yet covered')
c('')
c('- Clean Windows 10 22H2 / Windows 11 24H2 machines without developer tools or Visual C++ redistributables (release gate), including paths with spaces and Chinese characters on such machines.')
c('- Device removal / default-device change during a long live session (the handling exists but was not exercised by an automated test).')
c('- Any GPU acceleration.')
(ROOT / 'docs/COMPATIBILITY.md').write_text('\n'.join(compat) + '\n', encoding='utf-8')
print('Wrote docs/PROOF.md, docs/BENCHMARK.md and docs/COMPATIBILITY.md')
if REPORTS != ROOT/'reports':
    for name in ['PROOF.md','BENCHMARK.md','COMPATIBILITY.md']:
        path=ROOT/'docs'/name
        text=path.read_text('utf-8')
        for item in ['verification.json','stages/','boundaries.json','tokenizer.json','preprocessing.json','fixture-frontend.json','speech-gate.json','cli-failures.json','benchmark-threads.json','memory.json','encoder-diff-mandarin-0000.json','variant-evaluation.json','reference-global-attention/','gui-test.json','directml.json']:
            text=text.replace('reports/'+item,CONFIG['report_root']+'/'+item)
        path.write_text(text,encoding='utf-8')
